-- Email threads: groups messages into conversations
CREATE TABLE IF NOT EXISTS email_threads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  provider VARCHAR(50) NOT NULL DEFAULT 'hostinger',
  provider_thread_id VARCHAR(255),
  mailbox CITEXT NOT NULL,
  subject TEXT,
  from_email CITEXT,
  last_message_at TIMESTAMPTZ,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_email_threads_provider_thread ON email_threads (provider, provider_thread_id) WHERE provider_thread_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_email_threads_mailbox ON email_threads (mailbox);
CREATE INDEX IF NOT EXISTS idx_email_threads_status ON email_threads (status);
CREATE INDEX IF NOT EXISTS idx_email_threads_last_message ON email_threads (last_message_at DESC);

CREATE OR REPLACE FUNCTION update_email_threads_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_email_threads_updated_at ON email_threads;
CREATE TRIGGER update_email_threads_updated_at
  BEFORE UPDATE ON email_threads
  FOR EACH ROW EXECUTE FUNCTION update_email_threads_updated_at();

-- Individual emails linked to threads
CREATE TABLE IF NOT EXISTS emails (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  thread_id UUID NOT NULL REFERENCES email_threads(id) ON DELETE CASCADE,
  provider_message_id VARCHAR(255),
  message_id VARCHAR(255),
  in_reply_to VARCHAR(255),
  from_email CITEXT NOT NULL,
  to_email TEXT,
  cc_email TEXT,
  bcc_email TEXT,
  subject TEXT,
  body_text TEXT,
  body_html TEXT,
  received_at TIMESTAMPTZ,
  direction VARCHAR(20) NOT NULL DEFAULT 'inbound',
  raw_metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_emails_provider_message ON emails (provider_message_id) WHERE provider_message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_emails_thread ON emails (thread_id);
CREATE INDEX IF NOT EXISTS idx_emails_message_id ON emails (message_id);
CREATE INDEX IF NOT EXISTS idx_emails_in_reply_to ON emails (in_reply_to);
CREATE INDEX IF NOT EXISTS idx_emails_direction ON emails (direction);
CREATE INDEX IF NOT EXISTS idx_emails_received_at ON emails (received_at DESC);

-- AI email processing records: tracks classification, intent, and extraction for each email
CREATE TABLE IF NOT EXISTS ai_email_processing (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email_id UUID NOT NULL REFERENCES emails(id) ON DELETE CASCADE,
  classification VARCHAR(50),
  intent VARCHAR(100),
  confidence NUMERIC(3, 2),
  extracted_data JSONB,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  model_name VARCHAR(100),
  prompt_version VARCHAR(50),
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_email_processing_email ON ai_email_processing (email_id);
CREATE INDEX IF NOT EXISTS idx_ai_email_processing_status ON ai_email_processing (status);
CREATE INDEX IF NOT EXISTS idx_ai_email_processing_classification ON ai_email_processing (classification);

-- AI email replies: draft and sent replies generated by the AI
CREATE TABLE IF NOT EXISTS ai_email_replies (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email_id UUID NOT NULL REFERENCES emails(id) ON DELETE CASCADE,
  thread_id UUID NOT NULL REFERENCES email_threads(id) ON DELETE CASCADE,
  draft_body TEXT,
  final_body TEXT,
  decision VARCHAR(30),
  confidence NUMERIC(3, 2),
  approval_required BOOLEAN NOT NULL DEFAULT true,
  approved_by UUID,
  approved_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  provider_message_id VARCHAR(255),
  status VARCHAR(30) NOT NULL DEFAULT 'draft',
  failure_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_email_replies_email ON ai_email_replies (email_id);
CREATE INDEX IF NOT EXISTS idx_ai_email_replies_thread ON ai_email_replies (thread_id);
CREATE INDEX IF NOT EXISTS idx_ai_email_replies_status ON ai_email_replies (status);
CREATE INDEX IF NOT EXISTS idx_ai_email_replies_decision ON ai_email_replies (decision);

CREATE OR REPLACE FUNCTION update_ai_email_replies_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_ai_email_replies_updated_at ON ai_email_replies;
CREATE TRIGGER update_ai_email_replies_updated_at
  BEFORE UPDATE ON ai_email_replies
  FOR EACH ROW EXECUTE FUNCTION update_ai_email_replies_updated_at();
