ALTER TABLE users
  ADD COLUMN IF NOT EXISTS college VARCHAR(255),
  ADD COLUMN IF NOT EXISTS state VARCHAR(100),
  ADD COLUMN IF NOT EXISTS course VARCHAR(255);

ALTER TABLE manuscript_authors
  ADD COLUMN IF NOT EXISTS college VARCHAR(255),
  ADD COLUMN IF NOT EXISTS state VARCHAR(100),
  ADD COLUMN IF NOT EXISTS course VARCHAR(255);
